In [1]:
import numpy as np
import pandas as pd

In [2]:
type(None)

NoneType

In [4]:
None==None

True

In [6]:
n = None
n is None

True

In [7]:
np.__version__

'1.16.5'

In [13]:
i = '1234567'
i[:3]

'123'

In [14]:
i[3:]

'4567'

In [15]:
i[-1]

'7'

In [19]:
i[:-1]

'123456'

In [20]:
for k in range(5):
    print(k)

0
1
2
3
4


In [21]:
f=1_222_333.99

In [24]:
x = [1,2,3,4,5]
y = [10,20,30,40,50]
z = ['a','b','c','d','e']
[z + '->' + str(x) + ':' + str(y) for x,y,z in zip(x,y,z)]

['a->1:10', 'b->2:20', 'c->3:30', 'd->4:40', 'e->5:50']

In [25]:
[i**2 for i in range (1,5) if (i % 2 ==0)]

[4, 16]

In [26]:
python_list = [1,2,3,4,5]
np_array = np.array([python_list])

In [27]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.arange(12).shape

(12,)

In [33]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
x[1][1]

5

In [34]:
np_array % 2 == 0

array([[False,  True, False,  True, False]])

In [35]:
np_array [np_array <= 3]

array([1, 2, 3])

In [37]:
np.random.seed(10)
sales= np.array((100*np.random.rand(5)).astype(int))
sales

array([77,  2, 63, 74, 49])

In [42]:
location = []
for i in range(5):
    location.append('ABCDE'[i])
location

['A', 'B', 'C', 'D', 'E']

In [43]:
data = np.array([sales,location]).T
data

array([['77', 'A'],
       ['2', 'B'],
       ['63', 'C'],
       ['74', 'D'],
       ['49', 'E']], dtype='<U11')

In [45]:
df = pd.DataFrame(data, columns = ["Sales","Location"])
df

Sales Location
0    77        A
1     2        B
2    63        C
3    74        D
4    49        E

In [46]:
df.dtypes

Sales       object
Location    object
dtype: object

In [48]:
df.Sales = df.Sales.astype(int)
df.dtypes

Sales        int32
Location    object
dtype: object

In [51]:
df.describe()

Sales
count   5.000000
mean   53.000000
std    30.553232
min     2.000000
25%    49.000000
50%    63.000000
75%    74.000000
max    77.000000

In [53]:
df.std()

Sales    30.553232
dtype: float64

In [54]:
df.Location

0    A
1    B
2    C
3    D
4    E
Name: Location, dtype: object

In [55]:
df.Sales

0    77
1     2
2    63
3    74
4    49
Name: Sales, dtype: int32

In [57]:
df.loc[1:3,:]

Sales Location
1      2        B
2     63        C
3     74        D

In [58]:
df.iloc[-1,:]

Sales       49
Location     E
Name: 4, dtype: object

In [59]:
df.Sales.sort_values(ascending=False)

0    77
3    74
2    63
4    49
1     2
Name: Sales, dtype: int32

In [61]:
df['Month'] = pd.DataFrame(['Jan','Feb','Mar','Apr','May'])

In [62]:
df

Sales Location Month
0     77        A   Jan
1      2        B   Feb
2     63        C   Mar
3     74        D   Apr
4     49        E   May

In [63]:
del df['Month']

In [64]:
df

Sales Location
0     77        A
1      2        B
2     63        C
3     74        D
4     49        E